### ISSUE TITLE
problem with reading in "full_spp_csv.zip"

### ISSUE THREAD

**Issue by IZE85** [enricoschumann/BISdata#2]
I want to read in the so-called "Property prices: selected series (CSV)" dataset from BIS, which can be found under "full_spp_csv.zip".

When using the following code, I get the subsequent error message: 

**CODE**
fetch_dataset(dest.dir = dest.dir,
                                  dataset = "full_spp_csv.zip",
                                  bis.url = "https://www.bis.org/statistics/",
                                  exdir = dest.dir)
**END CODE**

**ERROR MESSAGE**
"trying URL 'https://www.bis.org/statistics/full_spp_csv.zip'
downloaded 112 KB

Error in read.table(tmp, header = TRUE, sep = ",", stringsAsFactors = FALSE,  : 
  duplicate 'row.names' are not allowed"
** END ERROR MESSAGE**

Extracting the dataset ("WS_SPP_csv_col.csv") from the zip file and reading in via R (read.table()) gives the desired result.

**CODE**
read.table("WS_SPP_csv_col.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
**END CODE**

**Comment by enricoschumann** [comment]
Thanks for the report, again :-) This is another quoting issue. I have changed the default setting accordingly in version-to-be 0.2-1. In that version, you can now also directly specify settings of `read.table`. For me, both examples work:

```r
library("BISdata")
packageVersion("BISdata")
## [1] ‘0.2.1’

dest.dir <- "~/Downloads/BIS"

data1 <- fetch_dataset(dest.dir = dest.dir,
                       dataset = "full_spp_csv.zip",
                       bis.url = "https://www.bis.org/statistics/",
                       exdir = dest.dir)


data2 <- fetch_dataset(dest.dir = dest.dir,
                       dataset = "full_credit_gap_csv.zip",
                       bis.url = "https://www.bis.org/statistics/",
                       exdir = dest.dir)
```

Could you give it a try, please? (Either from GitHub, or http://enricoschumann.net/R/packages/BISdata/)

**Comment by IZE85** [comment]
I updated to your version 0.2-1 and now everything works perfectly fine! Thank you for the quick turnaround!

**Comment by enricoschumann** [comment]
Very good. Then I'll close the issue. Thanks again.
